---
title: "Final Project"
author: "Tina Huang, Gunnar Mein, Jeff Li"
date: "7/27/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#import libraries
library(dplyr)
library(anytime)
library(lubridate)
library(tidyr)
library(ggplot2)
library(stargazer)
library(sandwich)
library(lmtest)
options(scipen=999)

```

Preprocessing the data

```{r data preprocessing}
#import files
rote_cov_original <- read.csv(file="/Users/jeff/Documents/MIDS/W241/logs/rote_cov.csv", sep=',') #covariates
rote_test_original <- read.csv(file="/Users/jeff/Documents/MIDS/W241/logs/rote_test.csv", sep=',') #test file

rote_cov_original$gender

```
```{r data 2}
#create copies
rote_cov <- rote_cov_original
rote_test <- rote_test_original

#convert unix epoch time to datetime
#cov
rote_cov$session_start_time <- as.POSIXct(rote_cov$session_start_time/1000, origin="1970-01-01")
rote_cov$cov_submit_time <- as.POSIXct(rote_cov$cov_submit_time/1000, origin="1970-01-01")

#test
rote_test$session_start_time <- as.POSIXct(rote_test$session_start_time/1000, origin="1970-01-01")
rote_test$test_submit_time <- as.POSIXct(rote_test$test_submit_time/1000, origin="1970-01-01")
rote_test$test_time <- rote_test$test_submit_time - rote_test$session_start_time

###remove rows with any NAs in the answers(indicates they did not complete the test)
rote_test <- rote_test %>% drop_na("a11", "a12", "a13", "a14", "a21", "a22", "a23","a24")

rote_test_baseline <- rote_test %>% filter(test == 'baseline')
rote_test_experiment <- rote_test %>% filter(test == 'experiment') %>% select('session_id','item_id1','a11','a12', 'a13', 'a14', 'a21', 'a22', 'a23','a24', 'item_id2', 'c11','c12', 'c13', 'c14', 'c21', 'c22', 'c23','c24')

rote_test <- inner_join(rote_test_baseline, rote_test_experiment, by="session_id" )


###remove rows with missing covariates
#covert age, remove outliers for age
rote_cov$age <- ifelse(as.numeric(as.character(rote_cov$age)) >100, NA, as.numeric(as.character(rote_cov$age)))
rote_cov <- rote_cov %>% drop_na("age")

#fix gender
rote_cov$gender <- ifelse(rote_cov$gender == 'other', NA, rote_cov$gender)


#on test file, establish if testee answer matches actual answer. if it matches, set var to 1, else 0. 
#notation will be o11, o12, etc (o is for outcome)
#x = baseline
#y = treatment
rote_test$o11x <- ifelse(rote_test$a11.x == rote_test$c11.x, 1, 0)
rote_test$o12x <- ifelse(rote_test$a12.x == rote_test$c12.x, 1, 0)
rote_test$o13x <- ifelse(rote_test$a13.x == rote_test$c13.x, 1, 0)
rote_test$o14x <- ifelse(rote_test$a14.x == rote_test$c14.x, 1, 0)
rote_test$o21x <- ifelse(rote_test$a21.x == rote_test$c21.x, 1, 0)
rote_test$o22x <- ifelse(rote_test$a22.x == rote_test$c22.x, 1, 0)
rote_test$o23x <- ifelse(rote_test$a23.x == rote_test$c23.x, 1, 0)
rote_test$o24x <- ifelse(rote_test$a24.x == rote_test$c24.x, 1, 0)

rote_test$o11y <- ifelse(rote_test$a11.y == rote_test$c11.y, 1, 0)
rote_test$o12y <- ifelse(rote_test$a12.y == rote_test$c12.y, 1, 0)
rote_test$o13y <- ifelse(rote_test$a13.y == rote_test$c13.y, 1, 0)
rote_test$o14y <- ifelse(rote_test$a14.y == rote_test$c14.y, 1, 0)
rote_test$o21y <- ifelse(rote_test$a21.y == rote_test$c21.y, 1, 0)
rote_test$o22y <- ifelse(rote_test$a22.y == rote_test$c22.y, 1, 0)
rote_test$o23y <- ifelse(rote_test$a23.y == rote_test$c23.y, 1, 0)
rote_test$o24y <- ifelse(rote_test$a24.y == rote_test$c24.y, 1, 0)






rote_test$score_pre <- rote_test$o11x + rote_test$o12x + rote_test$o13x + rote_test$o14x + rote_test$o21x + rote_test$o22x + rote_test$o23x + rote_test$o24x
rote_test$score_post <- rote_test$o11y + rote_test$o12y + rote_test$o13y + rote_test$o14y + rote_test$o21y + rote_test$o22y + rote_test$o23y + rote_test$o24y

rote_test$score =  rote_test$score_post - rote_test$score_pre


#on covariates file, sum knowledge scores together
rote_cov$knowledge_cov_pre <- rote_cov$knowledge1 + rote_cov$knowledge2 
rote_cov$knowledge_cov_post <- rote_cov$knowledge3 + rote_cov$knowledge4
rote_cov$prior_knowledge <- rote_cov$knowledge_cov_post + rote_cov$knowledge_cov_pre

#convert necessary columns to boolean
rote_test$treat <- ifelse(rote_test$treat == "false", 0 , 1)
rote_cov$treat <- ifelse(rote_cov$treat == "false", 0 , 1)


#get distinct ids
rote_test <- rote_test[!duplicated(rote_test$session_id),]
rote_cov <- rote_cov[!duplicated(rote_cov$session_id),]

#inner join 2 datasets
#dataset <- merge(rote_test, rote_cov, by="session_id")

dataset <- inner_join(rote_test, rote_cov, by="session_id" )

#set date filter based on start time in test file
#dataset <- dataset %>% filter(session_start_time.x > as.POSIXct("2020-07-24 20:00:00", tz="UTC")) 


#names(dataset)

dataset$treat <- dataset$treat.x
dataset$cluster <- dataset$cluster.x
dataset$gender <- as.factor(dataset$gender)
dataset <- dataset %>% filter %>% select("session_id", "score", "cluster", "gender", "age", "prior_knowledge", "treat","reading", "practice")

dataset
#nrow(dataset)

#nrow(rote_test)
#nrow(rote_cov)
```


## EDA, Regression modeling


```{r EDA, results='asis'}


#number of rows in the data

print(paste("After cleaning, the number of rows in our dataset is:", toString(nrow(dataset))))
print(paste("After cleaning, the number of observations in treatment is:", toString(sum(dataset$treat))))
print(paste("After cleaning, the number of observations in control is:", toString(nrow(dataset) - sum(dataset$treat))))

ggplot(dataset, aes(x=age)) + geom_histogram()

dataset_control <- dataset %>% filter(treat == 0)
dataset_treat <- dataset %>% filter(treat == 1)

dataset %>% ggplot(aes(x=score, fill=as.factor(treat)))+
  geom_bar(stat="count", position="dodge") +
  theme_minimal() +
  #scale_fill_brewer(palette="Dark2") +
  scale_fill_manual(values=c("#003262", "#FDB515"),
                    labels=c("Control", "Treatment"))+
 ylab("Frequency") + 
  ggtitle("Score difference between baseline and experiment") +
  theme(legend.title=element_blank())

ggplot(dataset, aes(x=gender)) + 
  geom_bar() +
  ggtitle("Distribution of Gender")


#names(dataset)

#dataset
unique(dataset$gender)
regression1 <- lm(score ~ treat + age + prior_knowledge + reading + gender + practice,data=dataset)
regression2 <- lm(score ~ treat ,data=dataset)


clustered_errors1 <- vcovCL_1c <- vcovCL(regression1, cluster = dataset[ , 'cluster'])
clustered_errors2 <- vcovCL_1c <- vcovCL(regression2, cluster = dataset[ , 'cluster'])

stargazer(dataset, 
                  header= F,
                  title = "Summary Table of Data", 
                  type="latex") #flip type between text and latex



stargazer(regression1, regression2, 
          header = F, 
          type = "latex", 
          omit.table.layout= "n", 
          keep.stat = c("adj.rsq", "n", "f", "ser", "aic", "wald"),
          se = list(sqrt(diag(clustered_errors1)),sqrt(diag(clustered_errors2))),
          star.cutoffs = c(0.05, 0.01, 0.001),
          title="Regression Results with Clustered Standard Errors")

```